config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  get 'basic_search' => 'apartments#basic_search'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'admin' => 'admin#index'
  put 'admin/:id' => 'admin#update'
  patch 'admin/:id' => 'admin#update'
  root 'apartments#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
        user = User.new
    end
    if user.has_role? :admin
        can :read, :all
        can :manage, :all
    elsif user.has_role? :creator
        can :read, :all
        can :manage, Apartment, user_id: user.id
    else user.add_role :viewer
        can :read, :all
    end
  end
end



# Define abilities for the passed in user here. For example:
#
#   user ||= User.new # guest user (not logged in)
#   if user.admin?
#     can :manage, :all
#   else
#     can :read, :all
#   end
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/apartment.rb
class Apartment < ApplicationRecord
    belongs_to :user
    validates :address, :city, :state, :country, :postal, :building_man, :phone, :hours, presence: true
    validates :state, length: { is: 2 }
    validates :postal, length: { is: 5 }
    validates :phone, length: { minimum: 10 }
    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
    validates_attachment :image, presence: true,
        content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
        size: { in: 0..10.megabytes }
    resourcify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:twitter]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.uid + "@twitter.com"
      user.password = Devise.friendly_token[0,20]
    end
  end

  after_create :assign_role

  def assign_role
      add_role(:creator)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize

    def index
        @users = User.all
    end

    def update
        user = User.find(params[:id])
        if user.has_role?(:creator)
            user.roles = []
            user.add_role(:admin)
        elsif user.has_role?(:admin) || user.has_role?(:viewer)
            user.roles = []
            user.add_role(:creator)
        end
        redirect_to '/admin'
    end

    private

    def authorize
        if !current_user.has_role? :admin
            render plain:"No access for you!"
        end
    end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
    @ability = Ability.new(current_user)
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = current_user.apartments.build
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_user.apartments.new(apartment_params)
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def basic_search
    @ability = Ability.new(current_user)
    @apartments = Apartment.basic_search(params[:basic_search])
    render 'index.html.erb'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:address, :city, :state, :country, :postal, :building_man, :phone, :hours, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.roles.last.name %></td>
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=admin", method: :PUT) do %>
          <input type="submit" value="Make Admin"/>
        <% end %>
      </td>
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=creator", method: :PUT) do %>
          <input type="submit" value="Make Creator"/>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', apartments_path %>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true, multipart: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :apartment_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :apartment_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :apartment_state %>
  </div>

  <div class="field">
      <%= form.label :country %>
      <%= form.text_field :country, id: :apartment_country %>
  </div>

  <div class="field">
      <%= form.label :postal %>
      <%= form.text_field :postal, id: :apartment_postal %>
  </div>

  <div class="field">
      <%= form.label :building_man %>
      <%= form.text_field :building_man, id: :apartment_building_man %>
  </div>

  <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone, id: :apartment_phone %>
  </div>

  <div class="field">
      <%= form.label :hours %>
      <%= form.text_field :hours, id: :apartment_hours %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>
<header>
    <div class="container">
        <h1>Apartments</h1>
        <form id="form" action="basic_search" method="get">
            <input type="text" name="basic_search" placeholder="Search">
            <input type="submit" value="Search">
        </form>
        <% if user_signed_in? %>
        <h5><%= if !current_user.nil?
            current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
        end %></h5>
        <button>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </button>
        <% else %>
        <button>
            <%= link_to('Login', new_user_session_path)  %>
        </button>
        <% end %>
    </div>
</header>

<main>
    <br>

    <table>
      <thead>
        <tr>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Country</th>
          <th>Postal</th>
          <th>Building Manager</th>
          <th>Contact Number</th>
          <th>Contact Hours</th>
          <th colspan="8"></th>
        </tr>
      </thead>

      <tbody>
        <% @apartments.each do |apartment| %>
            <tr>
                <td><%= apartment.address %></td>
                <td><%= apartment.city %></td>
                <td><%= apartment.state %></td>
                <td><%= apartment.country %></td>
                <td><%= apartment.postal %></td>
                <td><%= apartment.building_man %></td>
                <td><%= apartment.phone %></td>
                <td><%= apartment.hours %></td>
                <td><%= link_to 'Show', apartment %></td>
                <% if @ability.can? :manage, apartment %>
                    <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
                    <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <div class="management">
        <%= link_to 'New Apartment', new_apartment_path %>
        <% if @ability.can? :manage, :all %>
        <%= link_to 'Admin Management', admin_path %>
        <% end %>
    </div>
</main>


<footer>
    Hello World!
</footer>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @apartment.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @apartment.postal %>
</p>

<p>
  <strong>Building Manager:</strong>
  <%= @apartment.building_man %>
</p>

<p>
  <strong>Contact Number:</strong>
  <%= @apartment.phone %>
</p>

<p>
  <strong>Contact Hours:</strong>
  <%= @apartment.hours %>
</p>

<%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>

<br>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apartment Listings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>